---
title: "sim_data"
output: html_document
date: "2025-09-17"
---

```{r}
library(dplyr)
library(lubridate)
library(slider)

setwd('/users/coop/desktop/Fantasy')
```

```{r}

raw <- read.csv('2024/raw_schedule.csv')

index <- read.csv('2024/game_index.csv')

codes <- read.csv('code_index.csv')

raw$date <- mdy(raw$date)
index$date <- ymd(index$date)

```

```{r}
raw_h2a <- raw %>%
  mutate(
    home = if_else(order == "@", loser,  winner),
    away = if_else(order == "@", winner, loser),

    pts_home = if_else(order == "@", ptsL, ptsW),
    pts_away = if_else(order == "@", ptsW, ptsL),

    yds_home = if_else(order == "@", ydsL, ydsW),
    yds_away = if_else(order == "@", ydsW, ydsL),

    to_home  = if_else(order == "@", toL,  toW),
    to_away  = if_else(order == "@", toW,  toL)
  ) %>%
  select(date, home, away,
         pts_home, pts_away,
         yds_home, yds_away,
         to_home,  to_away)

index_out <- index %>%
  left_join(raw_h2a, by = c("date","home","away"))



```

```{r}
raw23 <- read.csv('2023/raw_sched.csv')

index23 <- read.csv('2023/game_index.csv')

raw23$date <- mdy(raw23$date)
index23$date <- mdy(index23$date)
```


```{r}
raw_h2a_23 <- raw23 %>%
  mutate(
    home = if_else(order == "@", loser,  winner),
    away = if_else(order == "@", winner, loser),

    pts_home = if_else(order == "@", ptsL, ptsW),
    pts_away = if_else(order == "@", ptsW, ptsL),

    yds_home = if_else(order == "@", ydsL, ydsW),
    yds_away = if_else(order == "@", ydsW, ydsL),

    to_home  = if_else(order == "@", toL,  toW),
    to_away  = if_else(order == "@", toW,  toL)
  ) %>%
  select(date, home, away,
         pts_home, pts_away,
         yds_home, yds_away,
         to_home,  to_away)

index_out23 <- index23 %>%
  left_join(raw_h2a, by = c("date","home","away"))

index_all <- rbind(index_out, index_out23)
```


```{r}
home_drives <- read.csv('2023/rollups/home_drives_rollup.csv')
vis_drives <- read.csv('2023/rollups/vis_drives_rollup.csv')

home_drives <- index_all %>% 
  select(home_code, away_code, home_id) %>% 
  right_join(home_drives, by = c("home_id" = "source_file"))

colnames(home_drives) <- c("team", "opp", "game_id", "drop1", "quarter",
                           "time", "los", "plays", "length", "net_yds",
                           "Result")

vis_drives <- index_all %>% 
  select(home_code, away_code, home_id) %>% 
  right_join(vis_drives, by = c("home_id" = "source_file"))

colnames(vis_drives) <- c("opp", "team", "game_id", "drop1", "quarter",
                           "time", "los", "plays", "length", "net_yds",
                           "Result")

home_drives23 <- home_drives
vis_drives23 <- vis_drives

drives <- rbind(home_drives24, home_drives23, vis_drives24, vis_drives23)


```

```{r}
drives <- drives %>% 
  mutate(td_flag = ifelse(Result == "Touchdown", 1, 0),
         fga_flag = ifelse(Result == "Field Goal" |
                             Result == "Missed FG" |
                             Result == "Blocked FG" |
                             Result == "Blocked FG, Downs", 1, 0),
         fgm_flag = ifelse(Result == "Field Goal", 1, 0),
         to_flag = ifelse(Result == "Interception" |
                            Result == "Fumble" |
                            Result == "Safety" |
                            Result == "Fumble, Safety", 1, 0),
         punt_flag = ifelse(Result == "Punt" |
                              Result == "Blocked Punt" |
                              Result == "Blocked Punt, Downs", 1, 0))
```

```{r}

drives <- index_all %>% 
  select(date, home_id) %>% 
  right_join(drives, by = c('home_id' = 'game_id'))

```

```{r}

teams_off <- drives %>% 
  group_by(team, home_id) %>% 
  summarise(n_drives = n(),
            tds_o = sum(td_flag),
            fga_o = sum(fga_flag),
            fgm_o = sum(fgm_flag),
            to_o = sum(to_flag),
            punt_o = sum(punt_flag))
  
teams_def <- drives %>% 
  group_by(opp, home_id) %>% 
  summarise(n_drives = n(),
            tds_d = sum(td_flag),
            fga_d = sum(fga_flag),
            fgm_d = sum(fgm_flag),
            to_d = sum(to_flag),
            punt_d = sum(punt_flag))
```

```{r}
teams <- teams_off %>% 
  inner_join(teams_def, by = c('home_id', 'team' = 'opp')) %>% 
  rename(drives_off = n_drives.x,
         drives_def = n_drives.y)

game_dates <- index_all %>% 
  select(home_id, date)
```

```{r}

teams <- teams %>% 
  right_join(game_dates, by = 'home_id')

```

```{r}

write.csv(head(teams, n=10), 'chat_sample.csv')

```

```{r}

teams_lag <- teams %>%
  mutate(date = as.Date(date)) %>%
  arrange(team, date) %>%
  group_by(team) %>%
  mutate(
    across(
      c(ends_with("_o"), ends_with("_off"), ends_with("_d"), ends_with("_def")),
      ~ slide_dbl(lag(.x), mean, .before = 4, .complete = TRUE),
      .names = "{.col}_avg5"
    )
  ) %>%
  ungroup()


```

```{r}

test_atl <- teams %>% 
  filter(team == "ATL")

test_atl_lag <- teams_lag %>% 
  filter(team == "ATL")

```

