---
title: "pts_modeling"
output: html_document
date: "2025-09-26"
---

```{r}
library(stats)
library(dplyr)
library(ggplot2)
library(tidyr)

```

```{r}

lm1 <- lm(pts ~ n_drives_d_avg5 + punt_d_avg5 + td_d_avg5 + fga_d_avg5 + fgm_d_avg5 +
            to_o_avg5 + n_drives_o_avg5 + punt_o_avg5 + td_o_avg5 + fga_o_avg5 + fgm_o_avg5 +
            to_o_avg5, data = obs)

```

```{r}

obs <- obs %>% 
  mutate(proj = (((td_o_avg5 + td_d_avg5)/2)*7)+
                (((fgm_o_avg5 + fgm_d_avg5)/2)*3))
obs <- obs %>% 
  filter(!(is.na(pts)))

obs <- obs %>% 
  mutate(proj_adj = proj * 1.0489)

obs <- obs %>% 
  mutate(error = proj_adj - pts)
```

```{r}

pts_proj <- obs %>% 
  select(game_id, team, pts, proj_adj)

```

```{r}
pts_proj <- pts_proj %>%
  group_by(game_id) %>%
  mutate(row = row_number()) %>%     # distinguish the two teams
  ungroup() %>%
  pivot_wider(
    id_cols = game_id,
    names_from = row,
    values_from = c(team, pts, proj_adj),
    names_glue = "{.value}{row}"
  )


```

```{r}

pts_proj <- pts_proj %>% 
  mutate(proj_spread = proj_adj1 - proj_adj2,
         act_spread = pts1 - pts2)

pts_proj <- pts_proj %>% 
  mutate(team1_win = ifelse(pts1 > pts2, 1,0),
         team1_win_proj = ifelse(proj_adj1 > proj_adj2,1,0)) %>% 
  mutate(correct = ifelse(team1_win == team1_win_proj, 1,0))
         

```

